# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with the Node.js image to build the application
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript files
RUN npm run build

# Use a smaller Node.js image for running the application
FROM node:20-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the build output and node_modules from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Set the entry point for the Docker container
ENTRYPOINT ["node", "build/index.js"]
